import 'package:flutter/widgets.dart';

class AppStrings {
  static final Map<String, Map<String, String>> _t = {
    'en': {
      // Common
      'account': 'Account',
      'home': 'Home',
      'favorites': 'Favorites',
      'current_email': 'Current Email',
      'new_email': 'New Email',
      'send_verification_code': 'Send Verification Code',
      'verification_code': 'Verification Code',
      'verify_update': 'Verify & Update',
      'email_updated': 'Email Updated',
      'email_updated_msg': 'Your email has been successfully updated.',
      'ok': 'OK',

      'settings': 'Settings',
      'notifications': 'Notifications',
      'news_notifications': 'News Notifications',
      'receive_all_news': 'Receive All News',
      'only_favorites_news': 'Only Favorite-Related News',
      'only_favorites_news_sub': 'Get updates related to your favorite leagues, teams, and players',
      'match_start': 'Match Start Alerts',
      'match_start_sub': 'Get notified when matches begin',
      'match_end': 'Match End Alerts',
      'match_end_sub': 'Get notified when matches end',
      'goal_only': 'Goal Notifications Only',
      'goal_only_sub': 'Receive instant alerts when your favorite team scores',
      'language': 'Language',
      'system_language': 'System Default',
      'arabic': 'Arabic (العربية)',
      'english': 'English',
      'turkish': 'Turkish (Türkçe)',
      'time_format': 'Time Format',
      'fmt_12': '12-hour format (AM/PM)',
      'fmt_24': '24-hour format',
      'location': 'Location',
      'location_title': 'Enable Location-based Notifications',
      'location_sub': 'Location data is used only to adjust notification times',
      'appearance': 'Appearance',
      'system_theme': 'System Default',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'share_feedback': 'Share & Feedback',
      'share_app': 'Share This App',
      'share_mock': 'Share invoked (mock)',
      'feedback_label': 'Send Feedback to Developers',
      'send': 'Send',
      'feedback_mock': 'Feedback sent (mock)',

      // Friends
      'friends': 'Friends',
      'search_friends': 'Search friends...',
      'friends_found': 'friends found',
      'no_friends_found': 'No friends found',
      'favorite_team': 'Favorite Team',
      'favorite_player': 'Favorite Player',
      'national_team': 'National Team',
      'message': 'Message',
      'view_profile': 'View Profile',
      'message_sent': 'Message sent!',
      'profile_viewed': 'Profile viewed',

      // Games
      'games': 'Games',
      'select_game_mode': 'Select Game Mode',
      'online_mode': 'Online Mode',
      'offline_mode': 'Offline Mode',
      'play_with_others': 'Play with friends online',
      'play_solo': 'Play alone offline',
      'challenge_thirty': 'Challenge of Thirty',
      'challenge_thirty_desc': 'Multiple football mini-games',
      'guess_player': 'Guess the Player',
      'guess_player_desc': 'Identify football stars',
      'football_quiz': 'Football Questions',
      'football_quiz_desc': 'Answer football riddles',
      'play_full_game': 'Play Full Game',
      'play_all_challenges': 'Experience all challenges',
      'select_sub_game': 'Or Select a Sub-Game',
      'what_do_you_know': 'What Do You Know?',
      'what_do_you_know_desc': 'Test your football knowledge',
      'the_auction': 'The Auction',
      'the_auction_desc': 'Bid for the best players',
      'the_bell': 'The Bell',
      'the_bell_desc': 'Quick reaction game',
      'guess_transfers': 'Guess Transfers',
      'guess_transfers_desc': 'Guess which team the player transferred to',
      'whos_the_outsider': "Find the Wrong Player",
      'whos_the_outsider_desc': 'Find the player who never played for the team',
      'common_club': 'Common Club',
      'common_club_desc': 'Find the club these players played for together',
      'find_common_club': 'Which club did these players play for together?',
      'jersey_number': 'Identify by Jersey Number',
      'jersey_number_desc': 'Guess the player from their jersey number',
      'players': 'Players',
      'find_outsider': 'Find the player who never played for',
      'question': 'Question',
      'your_score': 'Your Score',
      'game_over': 'Game Over',
      'excellent_performance': 'Excellent Performance!',
      'good_job': 'Good Job!',
      'play_again': 'Play Again',
      'correct': 'Correct!',
      
      // The Bell Game
      'your_turn': 'Your Turn!',
      'computer_thinking': 'Computer thinking...',
      'computer_answered': 'Computer answered',
      'computer_answered_correctly': 'Computer answered correctly',
      'computer_answered_wrong': 'Computer answered wrong',
      'question_passed_to_computer': 'Wrong! Question passed to computer',
      'computer_turn': 'Computer\'s Turn',
      'correct_answer': 'Correct Answer!',
      'wrong_answer': 'Wrong Answer!',
      'correct_answer_is': 'Correct answer is',
      'time_out': 'Time Out!',
      'didnt_answer_in_time': 'You didn\'t answer in time',
      'both_failed': 'Both failed. No points.',
      'opponent_chance': 'Opponent\'s chance now!',
      'computer_chance': 'Computer\'s turn...',
      'ready': 'Ready!',
      'vs': 'VS',
      'points': 'points',
      'you': 'You',
      'computer': 'Computer',
      'you_won': 'You Won!',
      'you_lost': 'You Lost!',
      'final_score': 'Final Score',
      'exit': 'Exit',
      'type_answer': 'Type your answer...',
      'submit': 'Submit',
      'wrong': 'Wrong!',
      'easy': 'Easy',
      'medium': 'Medium',
      'hard': 'Hard',
      'select_difficulty': 'Select Difficulty Level',
      'very_famous': 'Very Famous Players',
      'well_known': 'Well Known Players',
      'very_difficult': 'Very Difficult',
      'coming_soon': 'Coming Soon',
      'level': 'Level',
      'club': 'Club',
      'player': 'Player',
      'stadium': 'Stadium',
      'coach': 'Coach',
      'delete': 'Delete',
      'submit': 'Submit',
      'choose_quiz_type': 'Choose Quiz Type',
      'quiz_type_subtitle': 'Select what you want to guess',
      'guess_player_name': 'Guess the player name',
      'guess_coach_name': 'Guess the coach name',
      'guess_club_name': 'Guess the club name',
      'loading_questions': 'Loading questions...',
      'error_loading_questions': 'Failed to load questions',
      'go_back': 'Go Back',
      'letters': 'letters',
      'time_up': 'Time\'s Up!',
      'correct_answer': 'Correct Answer',
      'correct_answer_msg': 'Correct! Well done!',
      'guess_player_name': 'Guess Player Name',
      'enter_player_name': 'Enter the player name',
      'player_name': 'Player Name',
      'wrong_guess': 'Wrong! Try again',
      'computer_guessing': 'Computer is Guessing',
      'computer_is_thinking': 'Computer is thinking...',
      'cancel': 'Cancel',
      'verifying': 'Verifying...',
      'ai_thinking': 'AI is thinking...',
      'answer_analyzing': 'Analyzing answer...',
      'ai_loading_questions': '🤖 Loading questions from Gemini AI...',
      'ai_analyzing_answer': '🤖 Analyzing your answer...',
      'ai_checking_answer': 'AI is checking your answer...',
      'ai_correct_answer': '✅ Correct answer! +1 point',
      'ai_wrong_answer_prefix': '❌ Wrong answer! Correct answer: ',
      'ai_powered_by': 'Powered by Gemini AI',
      'wrong_answer': 'Wrong answer! Try the next one.',
      'congratulations': 'Congratulations!',
      'quiz_completed': 'You completed all questions!',
      'play_again': 'Play Again',
      'exit': 'Exit',
      'you_win': 'You Win!',
      'you_lose': 'You Lose',
      'computer_wins': 'Computer Wins!',
      'computer_failed': '❌ Computer failed! Your turn',
      'your_turn': '🎯 Your turn to answer!',
      'microphone_permission_required': 'Microphone permission is required',
      'speech_not_available': 'Speech recognition is not available',
      'final_score': 'Final Score',
      'time_out': '⏰ Time Out!',
      'both_failed': '❌ Both Failed - No Points',
      'seconds': 'seconds',
      'your_answer': 'Your answer...',
      'computer_thinking': 'Computer is thinking...',
      'current_bid': 'Current Bid',
      'your_turn_to_bid': 'Your Turn to Bid',
      'give_up': 'Give Up',
      'computer_deciding': 'Computer is deciding...',
      'you_need_answers': 'You need to give',
      'answers_given': 'Answers given',
      'type_answer': 'Type an answer...',
      'finish_answering': 'Finish Answering',
      'need_more_answers': 'You need more answers',
      'press_bell': 'Press the Bell!',
      'waiting_for_answer': 'Waiting for answer...',
      'guess_player_name': 'Guess the player name',
      'reveal_club': 'Reveal Next Club',
      'skip_question': 'Skip Question',
      'get_ready': 'Get Ready!',
      
      // Guess The Player Game
      'guess_the_player': 'Guess the Player',
      'your_player_is': 'Your Player is:',
      'ask_question': 'Ask a question...',
      'question_already_asked': 'This question was already asked!',
      'answer_yes': 'YES ✓',
      'answer_no': 'NO ✗',
      'asked_questions': 'Asked Questions:',
      'correct': 'Correct',
      'incorrect': 'Incorrect',
      'your_player': 'Your Player',
      'computer_player': 'Computer Player',
      'final_score': 'Final Score',
      'computer_asking': 'Computer is asking:',
      'you_pressed_first': 'You pressed first!',
      'computer_pressed_first': 'Computer pressed first!',
      'microphone_not_available': 'Microphone not available',
      'microphone_permission_denied': 'Microphone permission denied. Please enable it in settings.',
      'extracting_names': '🎤 Extracting names...',
      'recording_mention_players': '🎤 Recording... mention player names',
      'no_player_names_found': 'No player names found in text',
      'answers_added': 'answers added',
      'error_processing_voice': 'Error processing voice',
      'recording_error': 'Recording error',
      'total_available_count': 'Total available count',
      'analyzing': 'Analyzing...',
      'evaluating_computer_answers': 'Evaluating computer answers...',
      'loading_question': 'Loading question...',
      'listening': '🎤 Listening...',
      'thinking': 'Thinking...',
      'player_passed': 'Player passed',
      'pass_again_to_give_up': 'Pass again to give up',
      'player_gave_up_after_passes': 'Player gave up after 2 passes',
      'already_used': 'Already used!',
      'wrong_answer': 'Wrong answer!',
      'challenge_decision': 'Challenge',
      'challenge_accepted': 'Challenge accepted',
      'used_by_player_or_computer': 'Already used by you or computer',
      'ai_thinking': 'AI is thinking',
      'confirm_voice_answer': 'Confirm Voice Answer',
      'you_said': 'You said:',
      'is_this_correct': 'Is this what you said?',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'more_clubs': 'more clubs',
      'player_name': 'Player name...',
      'transfer': 'Transfer',
      'thirty_challenge': 'Thirty Challenge',
      'thirty_challenge_complete': 'Thirty Challenge Complete',
      'next_game': 'Next Game',
      'current_score': 'Current Score',
      'continue': 'Continue',
      'start_game': 'Start Game',
      'draw': 'Draw',
      'play_full_thirty_challenge': 'Play Full Thirty Challenge',
      'play_all_games_compete': 'Play all 4 games and compete for the championship',

      // Drawer
      'drawer_guest': 'Guest User',
      'drawer_welcome': 'Welcome Back!',
      'drawer_explore': 'Explore football world',
      'drawer_pro': 'Classico Pro',
      'drawer_games': 'Games',
      'drawer_games_sub': 'Play and compete',
      'drawer_leagues': 'League Standings',
      'drawer_leagues_sub': 'View rankings',
      'drawer_news': 'News',
      'drawer_news_sub': 'Latest updates',
      'drawer_transfers': 'Transfers',
      'drawer_transfers_sub': 'Player movements',
      'drawer_favorites': 'Favorites',
      'drawer_favorites_sub': 'Your favorite teams',
      'drawer_friends': 'Friends',
      'drawer_friends_sub': 'Connect with others',
      'drawer_profile': 'Profile',
      'drawer_profile_sub': 'Your account',
      'drawer_settings': 'Settings',
      'drawer_settings_sub': 'App preferences',
      'drawer_login_cta': 'Login to Save Favorites',

      'stats_title': 'Statistics',
      'game_statistics': 'Game Statistics',
      'overall_statistics': 'Overall Statistics',
      'total_games': 'Total Games',
      'total_wins': 'Total Wins',
      'total_score': 'Total Score',
      'win_rate': 'Win Rate',
      'played': 'Played',
      'best': 'Best',
      'average': 'Average',
      'no_games_played_yet': 'No games played yet',
      'clear_statistics': 'Clear Statistics',
      'clear_statistics_confirm': 'Are you sure you want to clear all statistics? This cannot be undone.',
      'clear': 'Clear',
      'statistics_cleared': 'Statistics cleared successfully',

      // Favorites Hub
      'fav_hub_title': 'Favorites',
      'fav_leagues': 'Favorite Leagues',
      'fav_clubs': 'Favorite Clubs',
      'fav_national': 'National Teams',
      'fav_players': 'Favorite Players',
      'fav_matches': 'Favorite Matches',
      'removed': 'Removed',
      'added': 'Added',
      'add': 'Add',
      'add_club_hint': 'Add a club (e.g. Real Madrid)',
      'no_fav_clubs': 'No favorite clubs yet',
      'add_player_hint': 'Add a player (e.g. Messi)',
      'no_fav_players': 'No favorite players yet',
      'no_fav_national': 'No favorite national teams yet',
      'add_national_hint': 'Add a team (e.g. Brazil)',
      'no_fav_matches': 'No favorite matches yet',

      // Transfers
      'transfers': 'Transfers',
      'recent_transfers': 'Recent Transfers',
      'confirmed_transfers': 'confirmed transfers',
      'no_transfers_available': 'No transfers available',
      'search_coming_soon': 'Search coming soon!',
      'filter_options_coming_soon': 'Filter options coming soon!',
      'search_transfers': 'Search transfers',
      'filter_transfers': 'Filter transfers',
      'age': 'Age',
      'position': 'Position',
      'transfer_details': 'Transfer Details',
      'from': 'From',
      'to': 'To',
      'transfer_fee': 'Transfer Fee',
      'contract': 'Contract',
      'signed': 'Signed',
      'official_club_statement': 'Official Club Statement',
      'read_from_official_source': 'Read from official source',
      'could_not_open_link': 'Could not open the link',

      // Account Hub
      'account_hub_title': 'Account Settings',
      'change_email': 'Change Email',
      'change_password': 'Change Password',
      'change_username': 'Change Username',
      'current_email': 'Current Email',
      'new_email': 'New Email',
      'send_verification_code': 'Send Verification Code',
      'verification_code': 'Verification Code',
      'verify_update': 'Verify & Update',
      'email_updated': 'Email Updated',
      'email_updated_msg': 'Your email has been successfully updated.',
      'ok': 'OK',
      
      // Password Change
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'save_password': 'Save Password',
      'required': 'Required',
      'min_8_chars': 'Min 8 characters',
      'add_uppercase': 'Add an uppercase letter',
      'add_lowercase': 'Add a lowercase letter',
      'add_digit': 'Add a digit',
      'add_symbol': 'Add a symbol',
      'passwords_not_match': 'Passwords do not match',
      'strength': 'Strength',
      
      // Username Change
      'current_username': 'Current Username',
      'new_username': 'New Username',
      'save_username': 'Save Username',
      'username_validation': '3-20 chars, letters/digits/_ only',
      'username_taken': 'Username already taken',

      // Home Screen
      'home_title': 'Classico',
      'live_matches': 'Live Matches',
      'recent_matches': 'Recent Matches',
      'upcoming_matches': 'Upcoming Matches',
      'no_matches': 'No matches available',

      // Match Details Screen
      'match_details': 'Match Details',
      'lineup': 'Lineup',
      'events': 'Events',
      'players': 'Players',
      'injuries': 'Injuries',
      'statistics': 'Statistics',
      'ratings': 'Ratings',
      'vs': 'VS',
      'add_to_favorites': 'Add to Favorites',
      'share_match': 'Share Match',
      'starting_xi': 'Starting XI',
      'substitutes': 'Substitutes',
      'formation': 'Formation',
      'years_old': 'yrs',
      'match_events': 'Match Events',
      'no_events': 'No events recorded yet',
      'goal': 'Goal',
      'assist': 'Assist',
      'yellow_card': 'Yellow Card',
      'red_card': 'Red Card',
      'substitution': 'Substitution',
      'penalty': 'Penalty',
      'own_goal': 'Own Goal',
      'minute': 'min',
      'team_statistics': 'Team Statistics',
      'possession': 'Possession',
      'shots': 'Shots',
      'shots_on_target': 'Shots on Target',
      'corners': 'Corners',
      'fouls': 'Fouls',
      'offsides': 'Offsides',
      'passes': 'Passes',
      'pass_accuracy': 'Pass Accuracy',
      'player_ratings': 'Player Ratings',
      'no_ratings': 'Ratings not available yet',
      'team_injuries': 'Team Injuries',
      'no_injuries': 'No injuries reported',
      'injury_type': 'Injury Type',
      'expected_return': 'Expected Return',
      'status': 'Status',
      'out': 'Out',
      'doubtful': 'Doubtful',
      'team_players': 'Team Players',
      'goalkeeper': 'Goalkeeper',
      'defender': 'Defender',
      'midfielder': 'Midfielder',
      'forward': 'Forward',

      // Player Info Screen
      'current_club': 'Current Club',
      'player_details': 'Player Details',
      'jersey_number': 'Jersey Number',
      'date_of_birth': 'Date of Birth',
      'nationality': 'Nationality',
      'height': 'Height',
      'weight': 'Weight',
      'preferred_foot': 'Preferred Foot',
      'season_statistics': 'Season Statistics',
      'matches': 'Matches',
      'goals': 'Goals',
      'assists': 'Assists',
      'cards': 'Cards',
      'minutes_played': 'Minutes Played',
      'career_history': 'Career History',
      'present': 'Present',
      'added_to_favorites': 'Added to favorites',
      'removed_from_favorites': 'Removed from favorites',
      'link_copied': 'Link copied to clipboard',

      // League Standings
      'standings': 'Standings',
      'no_standings_available': 'No standings available',
      'club_name': 'Club',
      'mp_short': 'MP',
      'w_short': 'W',
      'd_short': 'D',
      'l_short': 'L',
      'gf_short': 'GF',
      'ga_short': 'GA',
      'gd_short': 'GD',
      'pts_short': 'Pts',
      'champions_league': 'European Matches',
      'europa_league': 'Europa League',
      'relegation': 'Relegation',
      'european_matches': 'European Matches',
      'national_team_matches': 'National Team Matches',

      // News Screen
      'news_title': 'Football News',
      'filter_news': 'Filter News',
      'news_available': 'news available',
      'breaking_news': 'Breaking News',
      'latest_news': 'Latest News',
      'read_more': 'Read More',

      // Welcome Screen
      'welcome_title': 'Welcome to Classico',
      'welcome_subtitle': 'Get live scores, news, and updates',
      'get_started': 'Get Started',
      'login': 'Login',
      'login_title': 'Login',
      'login_subtitle': 'Sign in to continue',
      'continue_with_google': 'Continue with Google',
      'sign_in_failed': 'Sign-in failed',
      'choose_username': 'Choose a username',
      'pick_unique_username': 'Pick a unique username',
      'username_visible': 'This will be visible to other users.',
      'username': 'Username',
      'username_hint': 'e.g. footy_fan_10',
      'username_required': 'Username is required',
      'username_min_3': 'Minimum 3 characters',
      'username_invalid': 'Only letters, numbers, _ and . allowed',
      'username_taken': 'This username is taken. Please choose another.',
      'phone_number': 'Phone number',
      'add_recovery_phone': 'Add a recovery phone',
      'phone_security': 'Used for account recovery and security notifications.',
      'phone_hint': '+1 555 123 4567',
      'phone_required': 'Phone number is required',
      'phone_invalid': 'Please enter a valid phone number',
      'continue': 'Continue',
      'your_preferences': 'Your preferences',
      'personalize_experience': 'Personalize your experience',
      'favorite_player': 'Favorite player',
      'favorite_player_hint': 'e.g. Lionel Messi',
      'favorite_team': 'Favorite team',
      'favorite_team_hint': 'e.g. Barcelona',
      'national_team': 'National team',
      'national_team_hint': 'e.g. Argentina',
      'preferred_league': 'Preferred league',
      'choose_league': 'Please choose a league',
      'required': 'Required',
      'finish': 'Finish',
      'signup': 'Sign Up',
      'continue_guest': 'Continue as Guest',

      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'close': 'Close',
      'logout': 'Log Out',
      'change_profile_photo': 'Change Profile Photo',
      'choose_from_gallery': 'Choose from Gallery',
      'choose_photo_from_gallery': 'Choose a photo from the gallery',
      'take_photo': 'Take Photo',
      'use_camera_to_take_photo': 'Use the camera to take a new photo',
      'remove_photo': 'Remove Photo',
      'return_to_default_photo': 'Return to the default photo',
      'favorites_count': 'Favorites',
      'leagues': 'Leagues',
      'teams': 'Teams',
      'players': 'Players',
      'exit_app': 'Exit App',
      'exit_app_message': 'Are you sure you want to exit?',
      'logout_message': 'Are you sure you want to logout?',
      'logout_success': 'Logged out successfully',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'all': 'All',
      
      // Search Hub
      'search_hub_title': 'Search',
      'search_players': 'Search Players',
      'search_teams': 'Search Teams',
      'search_leagues': 'Search Leagues',
      'search_coaches': 'Search Coaches',
      'search_national_teams': 'Search National Teams',
      'search_stadiums': 'Search Stadiums',
      'search_players_hint': 'Search for players...',
      'search_teams_hint': 'Search for teams...',
      'search_leagues_hint': 'Search for leagues...',
      'search_coaches_hint': 'Search for coaches...',
      'search_national_teams_hint': 'Search for national teams...',
      'search_stadiums_hint': 'Search for stadiums...',
      'search_history': 'Search History',
      'clear': 'Clear',
      'no_results_found': 'No results found',
      'top_players': 'Top 10 Players',
      'top_teams': 'Top 10 Teams',
      'top_leagues': 'Top 10 Leagues',
      'top_coaches': 'Top 10 Coaches',
      'top_national_teams': 'Top 10 National Teams',
      'top_stadiums': 'Top 10 Stadiums',
      'ranking': 'Ranking',
      'teams': 'teams',
      
      // All Leagues
      'all_leagues_title': 'League Standings',
      'season': 'Season',
      'upcoming': 'Upcoming',
      'top_scorers_tab': 'Top Scorers',
      'top_assists_tab': 'Assists',
      'yellow_cards_tab': 'Yellow Cards',
      'red_cards_tab': 'Red Cards',
      'clean_sheets_tab': 'Clean Sheets',
      'history_tab': 'History',
      'goals': 'Goals',
      'assists': 'Assists',
      'matches': 'Matches',
      'yellow_cards': 'Yellow Cards',
      'red_cards': 'Red Cards',
      'clean_sheets': 'Clean Sheets',
      'wins': 'Wins',
      'no_data_available': 'No data available',
      'club_name': 'Club',
      'league_info': 'League Info',
      'sponsor': 'Sponsor',
      'unknown': 'Unknown',
      'champions': 'Champions',
      'reigning_champion': 'Reigning Champion',
      'record_champion': 'Record Champion',
      'founded': 'Founded',
      'country': 'Country',
      'ai_translation': 'AI Translation',
      'translated_by_ai_to': 'Translated by AI to',
      'return_to_original': 'Return to Original',
      'translate_news_desc': 'Translate this news to English or Turkish',
      'more_from': 'More from',
      'more_news_soon': 'More news coming soon...',
      'select_language_ai': 'Select the desired language — powered by Gemini AI',
      'write_message_here': 'Write your message to the admin here...',
      'please_write_message': 'Please write your message first',
      'sending_message': 'Sending your message...',
      'message_sent_successfully': 'Your message has been sent successfully. Thank you!',
      'error_sending_message': 'An error occurred while sending. Please try again later.',
      
      // Game Transitions & Results
      'current_score': 'Current Score',
      'you': 'You',
      'ai': 'AI',
      'next_game': 'Next Game',
      'final_score': 'Final Score',
      'you_won': 'You Won!',
      'you_lost': 'You Lost!',
      'its_a_tie': "It's a Tie!",
      'challenge_completed': 'Challenge Completed!',
      'play_again': 'Play Again',
      'exit': 'Exit',
      
      // Pause Menu
      'game_paused': 'Game Paused',
      'resume': 'Resume',
      'restart': 'Restart',
      'continue': 'Continue',
      
      // Match Status
      'finished': 'Finished',
      
      // Comments
      'comments': 'Comments',
      'match_data_not_available': 'Match data not available',
      'free_agent': 'Free Agent',
      'choose_reaction': 'Choose your reaction',
      'reply_to_comment': 'Reply to comment',
      'add_comment': 'Add a comment...',
      'show_all_comments': 'Show All',
      'show_language_comments': 'Language',
      'translate': 'Translate',
      'show_original_text': 'Show Original',
      'translation_success': 'Translation successful',
      'translation_error': 'Translation error:',
      'reply': 'Reply',
      'replies': 'Replies',
      'inappropriate_comment': 'Inappropriate Comment',
      'comment_violates_guidelines': 'Your comment violates community guidelines',
      'user_banned_24h': 'You have been banned for 24 hours',
      'ban_reason': 'Ban reason:',
      'remaining_ban_time': 'Remaining ban time:',
      'hours': 'hours',
      'cannot_comment_while_banned': 'You cannot comment while banned',
      'microphone_permission': 'Microphone Permission',
      'microphone_permission_description': 'Allow access to microphone for voice features',
      'enable_microphone': 'Enable Microphone',
      'disable_microphone': 'Disable Microphone',
      'microphone_enabled': 'Microphone is enabled',
      'microphone_disabled': 'Microphone is disabled',
      'add_friend': 'Add Friend',
      'enter_username': 'Enter the username of the friend you want to add',
      'add_to_favorites': 'Add to Favorites',
      'cancel': 'Cancel',
      'add': 'Add',
      'view': 'View',
      'user_not_found': 'User Not Found',
      'user_not_found_desc': 'The username you entered does not exist in the system',
      'friend_found': 'Friend found! Choose an action below',
      'add_directly': 'Add Directly',
      'find_friends_subtitle': 'Find and connect with friends',
      'search_username_hint': 'Search by username...',
      'you': 'You',
      'message': 'Message',
      'active_now': 'Active now',
      'type_message': 'Type a message...',
      'play_with_friends': 'Play with Friends',
      'challenge_your_friends': 'Challenge your friends',
      'select_game': 'Select Game',
      'choose_game_to_play': 'Choose a game to play',
      'select_friend': 'Select Friend',
      'choose_friend_to_play': 'Choose a friend to play with',
      'no_friends': 'No friends available',
      'new_message': 'New Message',
      'game_invite': 'Game Invite',
      'sent_you_message': 'sent you a message',
      'invites_you_to_play': 'invites you to play',
      'football_news': 'Football News',
      'account_notifications': 'Account',
      'no_football_news': 'No football news yet',
      'no_account_notifications': 'No account notifications yet',
      'now': 'Now',
      'minutes_ago': 'minutes ago',
      'hours_ago': 'hours ago',
      'days_ago': 'days ago',
      'ago': 'ago',
      'mark_all_as_read': 'Mark all as read',
      'clear_all': 'Clear all',
      'all_marked_as_read': 'All marked as read',
      'all_notifications_cleared': 'All notifications cleared',
      'notification_deleted': 'Notification deleted',
      'opened': 'Opened',
      'just_now': 'Just now',
      'minutes_ago_short': 'm ago',
      'hours_ago_short': 'h ago',
      'days_ago_short': 'd ago',
      'weeks_ago_short': 'w ago',
      'no_notifications': 'No notifications',
      'refresh_to_home': 'Refreshed to home',

      // Countries
      'spain': 'Spain',
      'england': 'England',
      'germany': 'Germany',
      'italy': 'Italy',
      'france': 'France',
      'portugal': 'Portugal',
      'netherlands': 'Netherlands',
      'brazil': 'Brazil',
      'argentina': 'Argentina',
      'saudi_arabia': 'Saudi Arabia',
      'egypt': 'Egypt',
      'morocco': 'Morocco',
      'algeria': 'Algeria',
      'tunisia': 'Tunisia',
      'qatar': 'Qatar',
      'uae': 'United Arab Emirates',
      'usa': 'USA',
      'belgium': 'Belgium',
      'croatia': 'Croatia',
      'uruguay': 'Uruguay',
      'turkey': 'Turkey',
      'mexico': 'Mexico',
      'japan': 'Japan',
    },
    'ar': {
      // Common
      'account': 'الحساب',
      'home': 'الرئيسية',
      'favorites': 'المفضلة',
      'current_email': 'البريد الحالي',
      'new_email': 'البريد الجديد',
      'send_verification_code': 'إرسال رمز التحقق',
      'verification_code': 'رمز التحقق',
      'verify_update': 'تحقق وتحديث',
      'email_updated': 'تم تحديث البريد',
      'email_updated_msg': 'تم تحديث بريدك الإلكتروني بنجاح.',
      'ok': 'حسناً',

      'settings': 'الإعدادات',
      'notifications': 'الإشعارات',
      'news_notifications': 'إشعارات الأخبار',
      'receive_all_news': 'استقبال كل الأخبار',
      'only_favorites_news': 'الأخبار المتعلقة بالمفضلة فقط',
      'only_favorites_news_sub': 'احصل على التحديثات المتعلقة بالدوريات والفرق واللاعبين المفضلين',
      'match_start': 'تنبيهات بدء المباراة',
      'match_start_sub': 'سيتم إعلامك عند بداية المباريات',
      'match_end': 'تنبيهات نهاية المباراة',
      'match_end_sub': 'سيتم إعلامك عند نهاية المباريات',
      'goal_only': 'تنبيهات الأهداف فقط',
      'goal_only_sub': 'احصل على تنبيه فوري عند تسجيل فريقك المفضل',
      'language': 'اللغة',
      'system_language': 'افتراضي النظام',
      'arabic': 'العربية',
      'english': 'الإنجليزية',
      'turkish': 'التركية (Türkçe)',
      'time_format': 'تنسيق الوقت',
      'fmt_12': 'تنسيق 12 ساعة (AM/PM)',
      'fmt_24': 'تنسيق 24 ساعة',
      'location': 'الموقع',
      'location_title': 'تفعيل الإشعارات حسب الموقع',
      'location_sub': 'تُستخدم بيانات الموقع لضبط أوقات الإشعارات فقط',
      'appearance': 'المظهر',
      'system_theme': 'افتراضي النظام',
      'light_mode': 'وضع النهار',
      'dark_mode': 'الوضع الداكن',
      'share_feedback': 'المشاركة والملاحظات',
      'share_app': 'مشاركة هذا التطبيق',
      'share_mock': 'تم استدعاء المشاركة (تجريبي)',
      'feedback_label': 'أرسل ملاحظاتك للمطورين',
      'send': 'إرسال',
      'feedback_mock': 'تم إرسال الملاحظات (تجريبي)',

      // Friends
      'friends': 'الأصدقاء',
      'search_friends': 'البحث عن أصدقاء...',
      'friends_found': 'صديق',
      'no_friends_found': 'لا يوجد أصدقاء',
      'favorite_team': 'الفريق المفضل',
      'favorite_player': 'اللاعب المفضل',
      'national_team': 'المنتخب الوطني',
      'message': 'رسالة',
      'view_profile': 'عرض الملف',
      'message_sent': 'تم إرسال الرسالة!',
      'profile_viewed': 'تم عرض الملف الشخصي',

      // Games
      'games': 'الألعاب',
      'select_game_mode': 'اختر وضع اللعب',
      'online_mode': 'اللعب عبر الإنترنت',
      'offline_mode': 'اللعب بدون إنترنت',
      'play_with_others': 'العب مع الأصدقاء عبر الإنترنت',
      'play_solo': 'العب بمفردك بدون إنترنت',
      'challenge_thirty': 'تحدي الثلاثين',
      'challenge_thirty_desc': 'ألعاب مصغرة متعددة',
      'guess_player': 'خمن اللاعب',
      'guess_player_desc': 'حدد نجوم كرة القدم',
      'football_quiz': 'أسئلة كرة القدم',
      'football_quiz_desc': 'أجب على الألغاز الكروية',
      'play_full_game': 'العب اللعبة كاملة',
      'play_all_challenges': 'جرب جميع التحديات',
      'select_sub_game': 'أو اختر لعبة فرعية',
      'what_do_you_know': 'ماذا تعرف؟',
      'what_do_you_know_desc': 'اختبر معلوماتك الكروية',
      'the_auction': 'المزاد',
      'the_auction_desc': 'زايد على أفضل اللاعبين',
      'the_bell': 'الجرس',
      'the_bell_desc': 'لعبة سرعة البديهة',
      'guess_transfers': 'خمن الانتقالات',
      'guess_transfers_desc': 'خمن الفريق الذي انتقل إليه اللاعب',
      'whos_the_outsider': 'اوجد اللاعب الخطأ',
      'whos_the_outsider_desc': 'اعثر على اللاعب الذي لم يلعب للفريق',
      'common_club': 'النادي المشترك',
      'common_club_desc': 'اعثر على النادي الذي لعب له هؤلاء اللاعبون معاً',
      'find_common_club': 'في أي نادي لعب هؤلاء اللاعبون معاً؟',
      'guess_jersey': 'خمِّن رقم القميص',
      'guess_jersey_desc': 'خمِّن اللاعب من رقم قميصه',
      'players': 'اللاعبون',
      'find_outsider': 'اعثر على اللاعب الذي لم يلعب لـ',
      'question': 'السؤال',
      'your_score': 'نتيجتك',
      'game_over': 'انتهت اللعبة',
      'excellent_performance': 'أداء ممتاز!',
      'good_job': 'أحسنت!',
      'play_again': 'العب مجدداً',
      'correct': 'صحيح!',
      'wrong': 'خطأ!',
      'easy': 'سهل',
      'medium': 'متوسط',
      'hard': 'صعب',
      'select_difficulty': 'اختر مستوى الصعوبة',
      'very_famous': 'لاعبون مشهورون جداً',
      'well_known': 'لاعبون معروفون',
      'very_difficult': 'صعب جداً',
      'coming_soon': 'قريباً',
      'level': 'المستوى',
      'club': 'نادي',
      'player': 'لاعب',
      'stadium': 'ملعب',
      'coach': 'مدرب',
      'delete': 'حذف',
      'submit': 'إرسال',
      'choose_quiz_type': 'اختر نوع السؤال',
      'quiz_type_subtitle': 'اختر ما تريد تخمينه',
      'guess_player_name': 'خمن اسم اللاعب',
      'guess_coach_name': 'خمن اسم المدرب',
      'guess_club_name': 'خمن اسم النادي',
      'loading_questions': 'جار تحضير الأسئلة...',
      'error_loading_questions': 'فشل تحميل الأسئلة',
      'go_back': 'العودة',
      'letters': 'حرف',
      'time_up': 'انتهى الوقت!',
      'correct_answer': 'الإجابة الصحيحة',
      'correct_answer_msg': 'صحيح! أحسنت!',
      'guess_player_name': 'خمّن اسم اللاعب',
      'enter_player_name': 'أدخل اسم اللاعب',
      'player_name': 'اسم اللاعب',
      'wrong_guess': 'خطأ! حاول مرة أخرى',
      'computer_guessing': 'الكمبيوتر يخمّن',
      'computer_is_thinking': 'الكمبيوتر يفكر...',
      'cancel': 'إلغاء',
      'verifying': 'جاري التحقق...',
      'ai_thinking': 'الذكاء الاصطناعي يفكر...',
      'answer_analyzing': 'جاري تحليل الإجابة...',
      'ai_loading_questions': '🤖 جاري تحميل الأسئلة من Gemini AI...',
      'ai_analyzing_answer': '🤖 جاري تحليل إجابتك...',
      'ai_checking_answer': 'الذكاء الاصطناعي يتحقق من إجابتك...',
      'ai_correct_answer': '✅ إجابة صحيحة! +1 نقطة',
      'ai_wrong_answer_prefix': '❌ إجابة خاطئة! الإجابة الصحيحة: ',
      'ai_powered_by': 'مدعوم بـ Gemini AI',
      'wrong_answer': 'إجابة خاطئة! جرب السؤال التالي.',
      'congratulations': 'تهانينا!',
      'quiz_completed': 'لقد أكملت جميع الأسئلة!',
      'play_again': 'العب مجدداً',
      'exit': 'خروج',
      'you_win': 'فزت!',
      'you_lose': 'خسرت',
      'computer_wins': 'الكمبيوتر فاز!',
      
      // The Bell Game
      'your_turn': 'دورك!',
      'computer_thinking': 'الكمبيوتر يفكر...',
      'computer_answered': 'الكمبيوتر أجاب',
      'computer_answered_correctly': 'الكمبيوتر أجاب بشكل صحيح',
      'computer_answered_wrong': 'الكمبيوتر أخطأ',
      'question_passed_to_computer': 'خطأ! تم تمرير السؤال للكمبيوتر',
      'computer_turn': 'دور الكمبيوتر',
      'correct_answer': 'إجابة صحيحة!',
      'wrong_answer': 'إجابة خاطئة!',
      'correct_answer_is': 'الإجابة الصحيحة',
      'time_out': 'انتهى الوقت!',
      'didnt_answer_in_time': 'لم تجب في الوقت المحدد',
      'both_failed': 'كلاهما أخطأ. لا نقاط.',
      'opponent_chance': 'فرصتك الآن!',
      'computer_chance': 'دور الكمبيوتر...',
      'ready': 'جاهز!',
      'vs': 'VS',
      'points': 'نقاط',
      'you': 'أنت',
      'computer': 'الكمبيوتر',
      'you_won': 'فزت!',
      'you_lost': 'خسرت!',
      'final_score': 'النتيجة النهائية',
      'type_answer': 'اكتب إجابتك...',
      'submit': 'إرسال',
      'computer_failed': '❌ الكمبيوتر أخطأ! دورك',
      'your_turn': '🎯 دورك للإجابة!',
      'microphone_permission_required': 'إذن الميكروفون مطلوب',
      'speech_not_available': 'التعرف على الصوت غير متوفر',
      'final_score': 'النتيجة النهائية',
      'time_out': '⏰ انتهى الوقت!',
      'both_failed': '❌ كلاهما أخطأ - لا نقاط',
      'seconds': 'ثانية',
      'your_answer': 'إجابتك...',
      'computer_thinking': 'الكمبيوتر يفكر...',
      'current_bid': 'المزايدة الحالية',
      'your_turn_to_bid': 'دورك للمزايدة',
      'give_up': 'استسلم',
      'computer_deciding': 'الكمبيوتر يقرر...',
      'you_need_answers': 'تحتاج إلى تقديم',
      'answers_given': 'الإجابات المقدمة',
      'type_answer': 'اكتب إجابة...',
      'finish_answering': 'انتهيت من الإجابة',
      'need_more_answers': 'تحتاج إلى المزيد من الإجابات',
      'press_bell': 'اضغط على الجرس!',
      'waiting_for_answer': 'في انتظار الإجابة...',
      'guess_player_name': 'خمن اسم اللاعب',
      'reveal_club': 'اكشف النادي التالي',
      'skip_question': 'تخطي السؤال',
      'get_ready': 'استعد!',
      
      // Guess The Player Game
      'guess_the_player': 'خمن اللاعب',
      'your_player_is': 'لاعبك هو:',
      'ask_question': 'اسأل سؤالاً...',
      'question_already_asked': 'هذا السؤال تم طرحه من قبل!',
      'answer_yes': 'نعم ✓',
      'answer_no': 'لا ✗',
      'asked_questions': 'الأسئلة المطروحة:',
      'correct': 'صحيح',
      'incorrect': 'خطأ',
      'your_player': 'لاعبك',
      'computer_player': 'لاعب الكمبيوتر',
      'final_score': 'النتيجة النهائية',
      'computer_asking': 'الكمبيوتر يسأل:',
      'you_pressed_first': 'ضغطت أولاً!',
      'computer_pressed_first': 'الكمبيوتر ضغط أولاً!',
      'microphone_not_available': 'الميكروفون غير متاح',
      'microphone_permission_denied': 'تم رفض إذن الميكروفون. يرجى تفعيله من الإعدادات.',
      'extracting_names': '🎤 جاري استخراج الأسماء...',
      'recording_mention_players': '🎤 جاري التسجيل... اذكر أسماء اللاعبين',
      'no_player_names_found': 'لم يتم العثور على أسماء لاعبين في النص',
      'answers_added': 'إجابات تمت إضافتها',
      'error_processing_voice': 'خطأ في معالجة الصوت',
      'recording_error': 'خطأ في التسجيل',
      'total_available_count': 'العدد الإجمالي المتاح',
      'analyzing': 'جاري التحليل...',
      'evaluating_computer_answers': 'جاري تقييم إجابات الكمبيوتر...',
      'loading_question': 'جاري تحميل السؤال...',
      'listening': '🎤 جاري الاستماع...',
      'thinking': 'جاري التفكير...',
      'player_passed': 'اللاعب مرر الدور',
      'pass_again_to_give_up': 'مرر مرة أخرى للاستسلام',
      'player_gave_up_after_passes': 'اللاعب استسلم بعد تمريرتين',
      'already_used': 'مستخدم سابقاً!',
      'wrong_answer': 'إجابة خاطئة!',
      'challenge_decision': 'طعن في القرار',
      'challenge_accepted': 'تم قبول الطعن',
      'used_by_player_or_computer': 'مستخدم سابقاً منك أو من الكمبيوتر',
      'ai_thinking': 'الذكاء الاصطناعي يفكر',
      'confirm_voice_answer': 'تأكيد الإجابة الصوتية',
      'you_said': 'قلت:',
      'is_this_correct': 'هل هذا ما قلته؟',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'more_clubs': 'أندية إضافية',
      'player_name': 'اسم اللاعب...',
      'transfer': 'انتقال',
      'thirty_challenge': 'تحدي الثلاثين',
      'thirty_challenge_complete': 'تم إنجاز تحدي الثلاثين',
      'next_game': 'اللعبة التالية',
      'current_score': 'النتيجة الحالية',
      'continue': 'متابعة',
      'start_game': 'ابدأ اللعبة',
      'draw': 'تعادل',
      'play_full_thirty_challenge': 'العب تحدي الثلاثين الكامل',
      'play_all_games_compete': 'العب جميع الألعاب الأربعة وتنافس على البطولة',

      // Drawer
      'drawer_guest': 'مستخدم ضيف',
      'drawer_welcome': 'مرحباً بعودتك!',
      'drawer_explore': 'استكشف عالم كرة القدم',
      'drawer_pro': 'Classico Pro',
      'drawer_games': 'الألعاب',
      'drawer_games_sub': 'العب وتنافس',
      'drawer_leagues': 'ترتيب الدوريات',
      'drawer_leagues_sub': 'شاهد التصنيفات',
      'drawer_news': 'الأخبار',
      'drawer_news_sub': 'آخر التحديثات',
      'drawer_transfers': 'الانتقالات',
      'drawer_transfers_sub': 'حركة اللاعبين',
      'drawer_favorites': 'المفضلة',
      'drawer_favorites_sub': 'فرقك المفضلة',
      'drawer_friends': 'الأصدقاء',
      'drawer_friends_sub': 'تواصل مع الآخرين',
      'drawer_profile': 'الملف الشخصي',
      'drawer_profile_sub': 'حسابك',
      'drawer_settings': 'الإعدادات',
      'drawer_settings_sub': 'تفضيلات التطبيق',
      'drawer_login_cta': 'سجّل الدخول لحفظ المفضلة',

      'stats_title': 'الإحصائيات',
      'game_statistics': 'إحصائيات الألعاب',
      'overall_statistics': 'الإحصائيات العامة',
      'total_games': 'إجمالي الألعاب',
      'total_wins': 'إجمالي الانتصارات',
      'total_score': 'إجمالي النقاط',
      'win_rate': 'معدل الفوز',
      'played': 'لعبت',
      'best': 'أفضل',
      'average': 'المتوسط',
      'no_games_played_yet': 'لم تلعب أي لعبة بعد',
      'clear_statistics': 'مسح الإحصائيات',
      'clear_statistics_confirm': 'هل أنت متأكد من مسح جميع الإحصائيات؟ لا يمكن التراجع عن هذا.',
      'clear': 'مسح',
      'statistics_cleared': 'تم مسح الإحصائيات بنجاح',

      // Favorites Hub
      'fav_hub_title': 'المفضلة',
      'fav_leagues': 'الدوريات المفضلة',
      'fav_clubs': 'الأندية المفضلة',
      'fav_national': 'المنتخبات',
      'fav_players': 'اللاعبون المفضلون',
      'fav_matches': 'المباريات المفضلة',
      'removed': 'تمت الإزالة',
      'added': 'تمت الإضافة',
      'add': 'إضافة',
      'add_club_hint': 'أضف نادي (مثال: ريال مدريد)',
      'no_fav_clubs': 'لا توجد أندية مفضلة بعد',
      'add_player_hint': 'أضف لاعب (مثال: ميسي)',
      'no_fav_players': 'لا يوجد لاعبون مفضلون بعد',
      'no_fav_national': 'لا توجد منتخبات مفضلة بعد',
      'add_national_hint': 'أضف منتخب (مثال: البرازيل)',
      'no_fav_matches': 'لا توجد مباريات مفضلة بعد',

      // Transfers
      'transfers': 'الانتقالات',
      'recent_transfers': 'الانتقالات الأخيرة',
      'confirmed_transfers': 'صفقة مؤكدة',
      'no_transfers_available': 'لا توجد انتقالات متاحة',
      'search_coming_soon': 'البحث قريباً!',
      'filter_options_coming_soon': 'خيارات التصفية قريباً!',
      'search_transfers': 'ابحث عن الانتقالات',
      'filter_transfers': 'تصفية الانتقالات',
      'age': 'العمر',
      'position': 'المركز',
      'transfer_details': 'تفاصيل الانتقال',
      'from': 'من',
      'to': 'إلى',
      'transfer_fee': 'قيمة الصفقة',
      'contract': 'العقد',
      'signed': 'تاريخ التوقيع',
      'official_club_statement': 'البيان الرسمي للنادي',
      'read_from_official_source': 'اقرأ من المصدر الرسمي',
      'could_not_open_link': 'تعذر فتح الرابط',

      // Account Hub
      'account_hub_title': 'إعدادات الحساب',
      'change_email': 'تغيير البريد',
      'change_password': 'تغيير كلمة المرور',
      'change_username': 'تغيير اسم المستخدم',
      'current_email': 'البريد الحالي',
      'new_email': 'البريد الجديد',
      'send_verification_code': 'إرسال رمز التحقق',
      'verification_code': 'رمز التحقق',
      'verify_update': 'تحقق وتحديث',
      'email_updated': 'تم تحديث البريد',
      'email_updated_msg': 'تم تحديث بريدك الإلكتروني بنجاح.',
      'ok': 'موافق',
      
      // Password Change
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
      'save_password': 'حفظ كلمة المرور',
      'required': 'مطلوب',
      'min_8_chars': 'الحد الأدنى 8 أحرف',
      'add_uppercase': 'أضف حرفًا كبيرًا',
      'add_lowercase': 'أضف حرفًا صغيرًا',
      'add_digit': 'أضف رقمًا',
      'add_symbol': 'أضف رمزًا',
      'passwords_not_match': 'كلمات المرور غير متطابقة',
      'strength': 'القوة',
      
      // Username Change
      'current_username': 'اسم المستخدم الحالي',
      'new_username': 'اسم المستخدم الجديد',
      'save_username': 'حفظ اسم المستخدم',
      'username_validation': '3-20 حرفًا، أحرف/أرقام/_ فقط',
      'username_taken': 'اسم المستخدم مستخدم بالفعل',

      // Home Screen
      'home_title': 'Classico',
      'live_matches': 'المباريات المباشرة',
      'recent_matches': 'المباريات الأخيرة',
      'upcoming_matches': 'المباريات القادمة',
      'no_matches': 'لا توجد مباريات متاحة',

      // Match Details Screen
      'match_details': 'تفاصيل المباراة',
      'lineup': 'التشكيلة',
      'events': 'الأحداث',
      'players': 'اللاعبون',
      'injuries': 'الإصابات',
      'statistics': 'الإحصائيات',
      'ratings': 'التقييمات',
      'vs': 'ضد',
      'add_to_favorites': 'إضافة للمفضلة',
      'share_match': 'مشاركة المباراة',
      'starting_xi': 'التشكيل الأساسي',
      'substitutes': 'البدلاء',
      'formation': 'الخطة',
      'years_old': 'سنة',
      'match_events': 'أحداث المباراة',
      'no_events': 'لم تسجل أحداث بعد',
      'goal': 'هدف',
      'assist': 'تمريرة حاسمة',
      'yellow_card': 'بطاقة صفراء',
      'red_card': 'بطاقة حمراء',
      'substitution': 'تبديل',
      'penalty': 'ركلة جزاء',
      'own_goal': 'هدف بالخطأ',
      'minute': 'د',
      'team_statistics': 'إحصائيات الفريق',
      'possession': 'الاستحواذ',
      'shots': 'التسديدات',
      'shots_on_target': 'التسديدات على المرمى',
      'corners': 'الركنيات',
      'fouls': 'الأخطاء',
      'offsides': 'التسللات',
      'passes': 'التمريرات',
      'pass_accuracy': 'دقة التمرير',
      'player_ratings': 'تقييمات اللاعبين',
      'no_ratings': 'التقييمات غير متوفرة بعد',
      'team_injuries': 'إصابات الفريق',
      'no_injuries': 'لا توجد إصابات مسجلة',
      'injury_type': 'نوع الإصابة',
      'expected_return': 'العودة المتوقعة',
      'status': 'الحالة',
      'out': 'خارج الملعب',
      'doubtful': 'مشكوك فيه',
      'team_players': 'لاعبو الفريق',
      'goalkeeper': 'حارس مرمى',
      'defender': 'مدافع',
      'midfielder': 'وسط',
      'forward': 'مهاجم',

      // Player Info Screen
      'current_club': 'النادي الحالي',
      'player_details': 'تفاصيل اللاعب',
      'jersey_number': 'رقم القميص',
      'date_of_birth': 'تاريخ الميلاد',
      'nationality': 'الجنسية',
      'height': 'الطول',
      'weight': 'الوزن',
      'preferred_foot': 'القدم المفضلة',
      'season_statistics': 'إحصائيات الموسم',
      'matches': 'المباريات',
      'goals': 'الأهداف',
      'assists': 'التمريرات الحاسمة',
      'cards': 'البطاقات',
      'minutes_played': 'الدقائق المشاركة',
      'career_history': 'التاريخ المهني',
      'present': 'حاليًا',
      'added_to_favorites': 'تمت الإضافة للمفضلة',
      'removed_from_favorites': 'تمت الإزالة من المفضلة',
      'link_copied': 'تم نسخ الرابط',

      // League Standings
      'standings': 'الترتيب',
      'no_standings_available': 'لا يوجد ترتيب متاح',
      'club_name': 'النادي',
      'mp_short': 'لعب',
      'w_short': 'ف',
      'd_short': 'ت',
      'l_short': 'خ',
      'gf_short': 'له',
      'ga_short': 'عليه',
      'gd_short': 'الفارق',
      'pts_short': 'النقاط',
      'champions_league': 'المباريات الأوروبية',
      'europa_league': 'الدوري الأوروبي',
      'relegation': 'الهبوط',
      'european_matches': 'المباريات الأوروبية',
      'national_team_matches': 'مباريات المنتخبات',

      // News Screen
      'news_title': 'أخبار كرة القدم',
      'filter_news': 'تصفية الأخبار',
      'news_available': 'خبر متاح',
      'breaking_news': 'أخبار عاجلة',
      'latest_news': 'آخر الأخبار',
      'read_more': 'اقرأ المزيد',

      // Welcome Screen
      'welcome_title': 'مرحباً بك في Classico',
      'welcome_subtitle': 'احصل على النتائج المباشرة والأخبار والتحديثات',
      'get_started': 'ابدأ',
      'login': 'تسجيل الدخول',
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'سجّل الدخول للمتابعة',
      'continue_with_google': 'متابعة باستخدام Google',
      'sign_in_failed': 'فشل تسجيل الدخول',
      'choose_username': 'اختر اسم مستخدم',
      'pick_unique_username': 'اختر اسم مستخدم فريد',
      'username_visible': 'سيكون مرئياً للمستخدمين الآخرين.',
      'username': 'اسم المستخدم',
      'username_hint': 'مثل: footy_fan_10',
      'username_required': 'اسم المستخدم مطلوب',
      'username_min_3': 'الحد الأدنى 3 أحرف',
      'username_invalid': 'الأحرف والأرقام و_ و. فقط',
      'username_taken': 'اسم المستخدم مستخدم بالفعل. اختر آخر.',
      'phone_number': 'رقم الهاتف',
      'add_recovery_phone': 'أضف رقم استرداد',
      'phone_security': 'يُستخدم لاسترداد الحساب وإشعارات الأمان.',
      'phone_hint': '+966 555 123 4567',
      'phone_required': 'رقم الهاتف مطلوب',
      'phone_invalid': 'الرجاء إدخال رقم هاتف صحيح',
      'continue': 'متابعة',
      'your_preferences': 'تفضيلاتك',
      'personalize_experience': 'خصّص تجربتك',
      'favorite_player': 'اللاعب المفضل',
      'favorite_player_hint': 'مثل: ليونيل ميسي',
      'favorite_team': 'الفريق المفضل',
      'favorite_team_hint': 'مثل: برشلونة',
      'national_team': 'المنتخب الوطني',
      'national_team_hint': 'مثل: الأرجنتين',
      'preferred_league': 'الدوري المفضل',
      'choose_league': 'الرجاء اختيار دوري',
      'required': 'مطلوب',
      'finish': 'إنهاء',
      'signup': 'إنشاء حساب',
      'continue_guest': 'متابعة كضيف',

      // Common
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'retry': 'إعادة المحاولة',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      'logout': 'تسجيل الخروج',
      'change_profile_photo': 'تغيير صورة الملف الشخصي',
      'choose_from_gallery': 'اختيار من المعرض',
      'choose_photo_from_gallery': 'اختر صورة من معرض الصور',
      'take_photo': 'التقاط صورة',
      'use_camera_to_take_photo': 'استخدم الكاميرا لالتقاط صورة جديدة',
      'remove_photo': 'إزالة الصورة',
      'return_to_default_photo': 'العودة إلى الصورة الافتراضية',
      'favorites_count': 'المفضلات',
      'leagues': 'الدوريات',
      'teams': 'الفرق',
      'players': 'اللاعبين',
      'exit_app': 'الخروج من التطبيق',
      'exit_app_message': 'هل أنت متأكد من الخروج؟',
      'logout_message': 'هل أنت متأكد من تسجيل الخروج؟',
      'logout_success': 'تم تسجيل الخروج بنجاح',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'search': 'بحث',
      'filter': 'تصفية',
      'sort': 'ترتيب',
      'all': 'الكل',
      
      // Search Hub
      'search_hub_title': 'البحث',
      'search_players': 'البحث عن لاعبين',
      'search_teams': 'البحث عن فرق',
      'search_leagues': 'البحث عن دوريات',
      'search_coaches': 'البحث عن مدربين',
      'search_national_teams': 'البحث عن منتخبات',
      'search_stadiums': 'البحث عن ملاعب',
      'search_players_hint': 'ابحث عن لاعبين...',
      'search_teams_hint': 'ابحث عن فرق...',
      'search_leagues_hint': 'ابحث عن دوريات...',
      'search_coaches_hint': 'ابحث عن مدربين...',
      'search_national_teams_hint': 'ابحث عن منتخبات...',
      'search_stadiums_hint': 'ابحث عن ملاعب...',
      'search_history': 'سجل البحث',
      'clear': 'مسح',
      'no_results_found': 'لا توجد نتائج',
      'top_players': 'أفضل 10 لاعبين',
      'top_teams': 'أفضل 10 فرق',
      'top_leagues': 'أفضل 10 دوريات',
      'top_coaches': 'أفضل 10 مدربين',
      'top_national_teams': 'أفضل 10 منتخبات',
      'top_stadiums': 'أفضل 10 ملاعب',
      'ranking': 'التصنيف',
      'teams': 'فريق',
      
      // All Leagues
      'all_leagues_title': 'ترتيب الدوريات',
      'season': 'الموسم',
      'upcoming': 'قادمة',
      'top_scorers_tab': 'الهدافون',
      'top_assists_tab': 'صناع الأهداف',
      'yellow_cards_tab': 'البطاقات الصفراء',
      'red_cards_tab': 'البطاقات الحمراء',
      'clean_sheets_tab': 'الشباك النظيفة',
      'history_tab': 'السجل التاريخي',
      'goals': 'أهداف',
      'assists': 'تمريرات',
      'matches': 'مباريات',
      'yellow_cards': 'بطاقات صفراء',
      'red_cards': 'بطاقات حمراء',
      'clean_sheets': 'شباك نظيفة',
      'wins': 'انتصارات',
      'no_data_available': 'لا تتوفر بيانات',
      'club_name': 'النادي',
      'league_info': 'تفاصيل الدوري',
      'sponsor': 'الراعي',
      'unknown': 'مجهول',
      'champions': 'الأبطال',
      'reigning_champion': 'البطل الحالي',
      'record_champion': 'الأكثر تتويجاً',
      'founded': 'التأسيس',
      'country': 'البلد',
      'ai_translation': 'ترجمة بالذكاء الاصطناعي',
      'translated_by_ai_to': 'مترجم بالذكاء الاصطناعي إلى',
      'return_to_original': 'العودة للأصل',
      'translate_news_desc': 'ترجم هذا الخبر إلى لغة أخرى',
      'more_from': 'المزيد من',
      'more_news_soon': 'المزيد من الأخبار قريباً...',
      'select_language_ai': 'اختر اللغة المطلوبة — مدعوم بتقنية Gemini AI',
      'write_message_here': 'اكتب رسالتك للمشرف هنا...',
      'please_write_message': 'الرجاء كتابة رسالتك أولاً',
      'sending_message': 'جاري إرسال رسالتك...',
      'message_sent_successfully': 'تم إرسال رسالتك بنجاح. شكراً لك!',
      'error_sending_message': 'حدث خطأ أثناء الإرسال. يرجى المحاولة لاحقاً.',
      
      // Game Transitions & Results
      'current_score': 'النتيجة الحالية',
      'you': 'أنت',
      'ai': 'الكمبيوتر',
      'next_game': 'اللعبة القادمة',
      'final_score': 'النتيجة النهائية',
      'you_won': 'لقد فزت!',
      'you_lost': 'لقد خسرت!',
      'its_a_tie': 'تعادل!',
      'challenge_completed': 'اكتمل التحدي!',
      'play_again': 'العب مرة أخرى',
      'exit': 'خروج',
      
      // Pause Menu
      'game_paused': 'اللعبة متوقفة',
      'resume': 'استئناف',
      'restart': 'إعادة تشغيل',
      'continue': 'متابعة',
      
      // Match Status
      'finished': 'انتهت',
      
      // Comments
      'comments': 'التعليقات',
      'match_data_not_available': 'لم تتوفر بيانات المباراة',
      'free_agent': 'لاعب حر',
      'choose_reaction': 'اختر رد فعلك',
      'reply_to_comment': 'الرد على تعليق',
      'add_comment': 'أضف تعليقاً...',
      'show_all_comments': 'اظهر الكل',
      'show_language_comments': 'اللغة',
      'translate': 'ترجمة',
      'show_original_text': 'عرض النص الأصلي',
      'translation_success': 'تمت الترجمة بنجاح',
      'translation_error': 'خطأ في الترجمة:',
      'reply': 'رد',
      'replies': 'ردود',
      'inappropriate_comment': 'تعليق مخالف للآداب',
      'comment_violates_guidelines': 'تعليقك يخالف معايير المجتمع',
      'user_banned_24h': 'تم حظرك لمدة 24 ساعة',
      'ban_reason': 'سبب الحظر:',
      'remaining_ban_time': 'الوقت المتبقي للحظر:',
      'hours': 'ساعات',
      'cannot_comment_while_banned': 'لا يمكنك التعليق أثناء الحظر',
      'microphone_permission': 'صلاحية الميكروفون',
      'microphone_permission_description': 'السماح بالوصول إلى الميكروفون لميزات الصوت',
      'enable_microphone': 'تفعيل الميكروفون',
      'disable_microphone': 'تعطيل الميكروفون',
      'microphone_enabled': 'الميكروفون مفعّل',
      'microphone_disabled': 'الميكروفون معطّل',
      'add_friend': 'إضافة صديق',
      'enter_username': 'أدخل اسم المستخدم للصديق الذي تريد إضافته',
      'add_to_favorites': 'إضافة إلى المفضلة',
      'cancel': 'إلغاء',
      'add': 'إضافة',
      'view': 'عرض',
      'user_not_found': 'لم يتم العثور على المستخدم',
      'user_not_found_desc': 'اسم المستخدم الذي أدخلته غير موجود في النظام',
      'friend_found': 'تم العثور على الصديق! اختر إجراء أدناه',
      'add_directly': 'إضافة مباشرة',
      'find_friends_subtitle': 'ابحث عن أصدقائك والتقط بهم',
      'search_username_hint': 'ابحث باسم المستخدم...',
      'you': 'أنت',
      'message': 'رسالة',
      'active_now': 'نشط الآن',
      'type_message': 'اكتب رسالة...',
      'play_with_friends': 'العب مع الأصدقاء',
      'challenge_your_friends': 'تحدى أصدقاءك',
      'select_game': 'اختر لعبة',
      'choose_game_to_play': 'اختر لعبة لتلعبها',
      'select_friend': 'اختر صديق',
      'choose_friend_to_play': 'اختر صديق لتلعب معه',
      'no_friends': 'لا توجد أصدقاء متاحين',
      'new_message': 'رسالة جديدة',
      'game_invite': 'دعوة لعب',
      'sent_you_message': 'أرسل لك رسالة',
      'invites_you_to_play': 'يدعوك للعب',
      'football_news': 'أخبار كرة القدم',
      'account_notifications': 'الحساب',
      'no_football_news': 'لا توجد أخبار كرة قدم حالياً',
      'no_account_notifications': 'لا توجد إشعارات حساب حالياً',
      'now': 'الآن',
      'minutes_ago': 'دقيقة',
      'hours_ago': 'ساعة',
      'days_ago': 'يوم',
      'ago': 'منذ',
      'mark_all_as_read': 'تحديد الكل كمقروء',
      'clear_all': 'حذف الكل',
      'all_marked_as_read': 'تم تحديد الكل كمقروء',
      'all_notifications_cleared': 'تم حذف جميع الإشعارات',
      'notification_deleted': 'تم حذف الإشعار',
      'opened': 'تم الفتح',
      'just_now': 'الآن للتو',
      'minutes_ago_short': 'د',
      'hours_ago_short': 'س',
      'days_ago_short': 'ي',
      'weeks_ago_short': 'أ',
      'no_notifications': 'لا توجد إشعارات',
      'refresh_to_home': 'تم التحديث إلى الصفحة الرئيسية',
      'add_league_hint': 'أضف دوري مفضل',
      'add_club_hint': 'أضف نادي (مثل ريال مدريد)',
      'add_national_hint': 'أضف فريق (مثل البرازيل)',
      'add_player_hint': 'أضف لاعب (مثل ميسي)',
      'save': 'حفظ',
      'add': 'إضافة',
      'clear': 'مسح',
      'search_history': 'سجل البحث',
      'top_teams': 'أفضل الفرق',
      'no_results_found': 'لم يتم العثور على نتائج',
      'search_teams_hint': 'ابحث عن الفرق...',
      'search_players': 'البحث عن اللاعبين',
      'search_teams': 'البحث عن الفرق',
      'search_leagues': 'البحث عن الدوريات',
      'search_coaches': 'البحث عن المدربين',
      'search_national_teams': 'البحث عن الفرق الوطنية',
      'search_stadiums': 'البحث عن الملاعب',
      'search_hub_title': 'بحث',
      'cancel': 'إلغاء',
      'change': 'تغيير',
      'username_change_affects': 'تغيير اسم المستخدم يؤثر على كيفية ظهور اسمك في الأقسام الاجتماعية والأصدقاء.',
      'confirm_password_change': 'هل أنت متأكد من أنك تريد تغيير كلمة المرور؟',
      'no_best_scores': 'لا توجد أفضل النتائج حتى الآن! ابدأ باللعب لتسجيل الأرقام القياسية! 🎯',
      'play_games_unlock_achievements': 'العب الألعاب لفتح الإنجازات! 🎯',

      // Countries
      'spain': 'إسبانيا',
      'england': 'إنكلترا',
      'germany': 'ألمانيا',
      'italy': 'إيطاليا',
      'france': 'فرنسا',
      'portugal': 'البرتغال',
      'netherlands': 'هولندا',
      'brazil': 'البرازيل',
      'argentina': 'الأرجنتين',
      'saudi_arabia': 'المملكة العربية السعودية',
      'egypt': 'مصر',
      'morocco': 'المغرب',
      'algeria': 'الجزائر',
      'tunisia': 'تونس',
      'qatar': 'قطر',
      'uae': 'الإمارات العربية المتحدة',
      'usa': 'الولايات المتحدة الأمريكية',
      'belgium': 'بلجيكا',
      'croatia': 'كرواتيا',
      'uruguay': 'الأوروغواي',
      'turkey': 'تركيا',
      'mexico': 'المكسيك',
      'japan': 'اليابان',
    },
    'tr': {
      // Common
      'account': 'Hesap',
      'home': 'Ana Sayfa',
      'favorites': 'Favoriler',
      'current_email': 'Mevcut E-posta',
      'new_email': 'Yeni E-posta',
      'send_verification_code': 'Doğrulama Kodunu Gönder',
      'verification_code': 'Doğrulama Kodu',
      'verify_update': 'Doğrula ve Güncelle',
      'email_updated': 'E-posta Güncellendi',
      'email_updated_msg': 'E-posta adresiniz başarıyla güncellendi.',
      'ok': 'Tamam',

      'settings': 'Ayarlar',
      'notifications': 'Bildirimler',
      'news_notifications': 'Haber Bildirimleri',
      'receive_all_news': 'Tüm Haberleri Al',
      'only_favorites_news': 'Sadece Favorilerle İlgili Haberler',
      'only_favorites_news_sub': 'Favori lig, takım ve oyuncularla ilgili güncellemeleri alın',
      'match_start': 'Maç Başlangıç Uyarıları',
      'match_start_sub': 'Maçlar başladığında bildirim alın',
      'match_end': 'Maç Bitiş Uyarıları',
      'match_end_sub': 'Maçlar bittiğinde bildirim alın',
      'goal_only': 'Sadece Gol Bildirimleri',
      'goal_only_sub': 'Favori takımınız gol attığında anında bildirim alın',
      'language': 'Dil',
      'system_language': 'Sistem Varsayılanı',
      'arabic': 'Arapça (العربية)',
      'english': 'İngilizce',
      'turkish': 'Türkçe',
      'time_format': 'Zaman Biçimi',
      'fmt_12': '12 saat (ÖÖ/ÖS)',
      'fmt_24': '24 saat',
      'location': 'Konum',
      'location_title': 'Konuma Dayalı Bildirimleri Etkinleştir',
      'location_sub': 'Konum verileri yalnızca bildirim saatlerini ayarlamak için kullanılır',
      'appearance': 'Görünüm',
      'system_theme': 'Sistem Varsayılanı',
      'light_mode': 'Açık Mod',
      'dark_mode': 'Koyu Mod',
      'share_feedback': 'Paylaş ve Geri Bildirim',
      'share_app': 'Bu Uygulamayı Paylaş',
      'share_mock': 'Paylaşım çağrıldı (deneme)',
      'feedback_label': 'Geliştiricilere Geri Bildirim Gönder',
      'send': 'Gönder',
      'feedback_mock': 'Geri bildirim gönderildi (deneme)',

      // Friends
      'friends': 'Arkadaşlar',
      'search_friends': 'Arkadaş ara...',
      'friends_found': 'arkadaş bulundu',
      'no_friends_found': 'Arkadaş bulunamadı',
      'favorite_team': 'Favori Takım',
      'favorite_player': 'Favori Oyuncu',
      'national_team': 'Milli Takım',
      'message': 'Mesaj',
      'view_profile': 'Profili Görüntüle',
      'message_sent': 'Mesaj gönderildi!',
      'profile_viewed': 'Profil görüntülendi',

      // Games
      'games': 'Oyunlar',
      'select_game_mode': 'Oyun Modunu Seç',
      'online_mode': 'Çevrimiçi Mod',
      'offline_mode': 'Çevrimdışı Mod',
      'play_with_others': 'Arkadaşlarınla çevrimiçi oyna',
      'play_solo': 'Çevrimdışı tek başına oyna',
      'challenge_thirty': 'Otuzun Meydan Okuması',
      'challenge_thirty_desc': 'Çoklu futbol mini oyunları',
      'guess_player': 'Oyuncuyu Tahmin Et',
      'guess_player_desc': 'Futbol yıldızlarını tanımla',
      'football_quiz': 'Futbol Soruları',
      'football_quiz_desc': 'Futbol bilmecelerini çöz',
      'play_full_game': 'Tam Oyunu Oyna',
      'play_all_challenges': 'Tüm meydan okumaları dene',
      'select_sub_game': 'Veya Bir Alt Oyun Seç',
      'what_do_you_know': 'Ne Biliyorsun?',
      'what_do_you_know_desc': 'Futbol bilginizi test edin',
      'the_auction': 'Müzayede',
      'the_auction_desc': 'En iyi oyuncular için teklif ver',
      'the_bell': 'Çan',
      'the_bell_desc': 'Hızlı tepki oyunu',
      'guess_transfers': 'Transferleri Tahmin Et',
      'guess_transfers_desc': 'Oyuncunun hangi takıma transfer olduğunu tahmin edin',
      'whos_the_outsider': 'Yanlış Oyuncuyu Bul',
      'whos_the_outsider_desc': 'Takımda hiç oynamayan oyuncuyu bulun',
      'common_club': 'Ortak Kulüp',
      'common_club_desc': 'Bu oyuncuların birlikte oynadığı kulübü bulun',
      'find_common_club': 'Bu oyuncular hangi kulüpte birlikte oynadı?',
      'guess_jersey': 'Forma Numarasını Tahmin Et',
      'guess_jersey_desc': 'Oyuncuyu forma numarasından tahmin edin',
      'players': 'Oyuncular',
      'find_outsider': 'Şu takımda hiç oynamayan oyuncuyu bulun:',
      'question': 'Soru',
      'your_score': 'Skorunuz',
      'game_over': 'Oyun Bitti',
      'excellent_performance': 'Mükemmel Performans!',
      'good_job': 'Aferin!',
      'play_again': 'Tekrar Oyna',
      'correct': 'Doğru!',
      'wrong': 'Yanlış!',
      'easy': 'Kolay',
      'medium': 'Orta',
      'hard': 'Zor',
      'select_difficulty': 'Zorluk Seviyesini Seç',
      'very_famous': 'Çok Ünlü Oyuncular',
      'well_known': 'Tanınmış Oyuncular',
      'very_difficult': 'Çok Zor',
      'coming_soon': 'Yakında',
      'level': 'Seviye',
      'club': 'Kulüp',
      'player': 'Oyuncu',
      'stadium': 'Stadyum',
      'coach': 'Antrenör',
      'delete': 'Sil',
      'submit': 'Gönder',
      'choose_quiz_type': 'Bilgi Yarışması Türünü Seç',
      'quiz_type_subtitle': 'Ne tahmin etmek istediğini seç',
      'guess_player_name': 'Oyuncu adını tahmin et',
      'guess_coach_name': 'Antrenör adını tahmin et',
      'guess_club_name': 'Kulüp adını tahmin et',
      'loading_questions': 'Sorular hazırlanıyor...',
      'error_loading_questions': 'Sorular yüklenemedi',
      'go_back': 'Geri Dön',
      'letters': 'harf',
      'time_up': 'Süre Bitti!',
      'correct_answer': 'Doğru Cevap',
      'correct_answer_msg': 'Doğru! Aferin!',
      'guess_player_name': 'Oyuncu Adını Tahmin Et',
      'enter_player_name': 'Oyuncu adını girin',
      'player_name': 'Oyuncu Adı',
      'wrong_guess': 'Yanlış! Tekrar dene',
      'computer_guessing': 'Bilgisayar Tahmin Ediyor',
      'computer_is_thinking': 'Bilgisayar düşünüyor...',
      'type_answer': 'Bir cevap yazın...',
      'finish_answering': 'Cevaplamayı Bitir',
      'need_more_answers': 'Daha fazla cevaba ihtiyacınız var',
      'cancel': 'İptal',
      'verifying': 'Doğrulanıyor...',
      'ai_thinking': 'Yapay zeka düşünüyor...',
      'answer_analyzing': 'Cevap analiz ediliyor...',
      'ai_loading_questions': '🤖 Gemini AI\'dan sorular yükleniyor...',
      'ai_analyzing_answer': '🤖 Cevabınız analiz ediliyor...',
      'ai_checking_answer': 'Yapay zeka cevabınızı kontrol ediyor...',
      
      // The Bell Game
      'your_turn': 'Senin Sıran!',
      'computer_thinking': 'Bilgisayar düşünüyor...',
      'computer_answered': 'Bilgisayar cevapladı',
      'computer_answered_correctly': 'Bilgisayar doğru cevapladı',
      'computer_answered_wrong': 'Bilgisayar yanlış cevapladı',
      'question_passed_to_computer': 'Yanlış! Soru bilgisayara geçti',
      'computer_turn': 'Bilgisayarın Sırası',
      'correct_answer': 'Doğru Cevap!',
      'wrong_answer': 'Yanlış Cevap!',
      'correct_answer_is': 'Doğru cevap',
      'time_out': 'Süre Bitti!',
      'didnt_answer_in_time': 'Zamanında cevaplayamadınız',
      'both_failed': 'İkisi de başarısız. Puan yok.',
      'opponent_chance': 'Şimdi senin şansın!',
      'computer_chance': 'Bilgisayarın sırası...',
      'ready': 'Hazır!',
      'vs': 'VS',
      'points': 'puan',
      'you': 'Sen',
      'computer': 'Bilgisayar',
      'you_won': 'Kazandınız!',
      'you_lost': 'Kaybettiniz!',
      'final_score': 'Son Skor',
      'type_answer': 'Cevabınızı yazın...',
      'submit': 'Gönder',
      'ai_correct_answer': '✅ Doğru cevap! +1 puan',
      'ai_wrong_answer_prefix': '❌ Yanlış cevap! Doğru cevap: ',
      'ai_powered_by': 'Gemini AI ile desteklenmektedir',
      'wrong_answer': 'Yanlış cevap! Bir sonrakini dene.',
      'congratulations': 'Tebrikler!',
      'quiz_completed': 'Tüm soruları tamamladınız!',
      'play_again': 'Tekrar Oyna',
      'exit': 'Çıkış',
      'you_win': 'Kazandın!',
      'you_lose': 'Kaybettin',
      'computer_wins': 'Bilgisayar Kazandı!',
      'computer_failed': '❌ Bilgisayar yanlış! Sıran',
      'your_turn': '🎯 Cevap verme sıran!',
      'microphone_permission_required': 'Mikrofon izni gerekli',
      'speech_not_available': 'Ses tanıma kullanılamıyor',
      'final_score': 'Final Skor',
      'time_out': '⏰ Süre Doldu!',
      'both_failed': '❌ Her İkisi de Başarısız - Puan Yok',
      
      // Guess The Player Game
      'guess_the_player': 'Oyuncuyu Tahmin Et',
      'your_player_is': 'Oyuncunuz:',
      'ask_question': 'Soru sor...',
      'question_already_asked': 'Bu soru zaten soruldu!',
      'answer_yes': 'EVET ✓',
      'answer_no': 'HAYIR ✗',
      'asked_questions': 'Sorulan Sorular:',
      'correct': 'Doğru',
      'incorrect': 'Yanlış',
      'your_player': 'Oyuncunuz',
      'computer_player': 'Bilgisayar Oyuncusu',
      'final_score': 'Final Skoru',
      'computer_asking': 'Bilgisayar soruyor:',
      'you_pressed_first': 'İlk sen bastın!',
      'computer_pressed_first': 'Bilgisayar ilk bastı!',
      'microphone_not_available': 'Mikrofon mevcut değil',
      'microphone_permission_denied': 'Mikrofon izni reddedildi. Lütfen ayarlardan etkinleştirin.',
      'extracting_names': '🎤 İsimler çıkarılıyor...',
      'recording_mention_players': '🎤 Kayıt ediliyor... oyuncu isimlerini söyleyin',
      'no_player_names_found': 'Metinde oyuncu isimleri bulunamadı',
      'answers_added': 'cevap eklendi',
      'error_processing_voice': 'Ses işleme hatası',
      'recording_error': 'Kayıt hatası',
      'total_available_count': 'Toplam mevcut sayı',
      'analyzing': 'Analiz ediliyor...',
      'evaluating_computer_answers': 'Bilgisayar cevapları değerlendiriliyor...',
      'loading_question': 'Soru yükleniyor...',
      'listening': '🎤 Dinleniyor...',
      'thinking': 'Düşünüyor...',
      'player_passed': 'Oyuncu pas geçti',
      'pass_again_to_give_up': 'Pes etmek için tekrar pas geç',
      'player_gave_up_after_passes': 'Oyuncu 2 pas sonra pes etti',
      'already_used': 'Zaten kullanıldı!',
      'wrong_answer': 'Yanlış cevap!',
      'challenge_decision': 'İtiraz Et',
      'challenge_accepted': 'İtiraz kabul edildi',
      'used_by_player_or_computer': 'Sizin veya bilgisayar tarafından kullanıldı',
      'ai_thinking': 'Yapay zeka düşünüyor',
      'confirm_voice_answer': 'Sesli Cevabı Onayla',
      'you_said': 'Söyledin:',
      'is_this_correct': 'Söylediğiniz bu mu?',
      'confirm': 'Onayla',
      'cancel': 'İptal',

      // Drawer
      'drawer_guest': 'Misafir Kullanıcı',
      'drawer_welcome': 'Tekrar Hoş Geldin!',
      'drawer_explore': 'Futbol dünyasını keşfet',
      'drawer_pro': 'Classico Pro',
      'drawer_games': 'Oyunlar',
      'drawer_games_sub': 'Oyna ve yarış',
      'drawer_leagues': 'Lig Sıralamaları',
      'drawer_leagues_sub': 'Sıralamaları görüntüle',
      'drawer_news': 'Haberler',
      'drawer_news_sub': 'Son güncellemeler',
      'drawer_transfers': 'Transferler',
      'drawer_transfers_sub': 'Oyuncu hareketleri',
      'drawer_favorites': 'Favoriler',
      'drawer_favorites_sub': 'Favori takımların',
      'drawer_friends': 'Arkadaşlar',
      'drawer_friends_sub': 'Başkalarıyla bağlantı kur',
      'drawer_profile': 'Profil',
      'drawer_profile_sub': 'Hesabınız',
      'drawer_settings': 'Ayarlar',
      'drawer_settings_sub': 'Uygulama tercihleri',
      'drawer_login_cta': 'Favorileri kaydetmek için giriş yap',

      'stats_title': 'İstatistikler',
      'game_statistics': 'Oyun İstatistikleri',
      'overall_statistics': 'Genel İstatistikler',
      'total_games': 'Toplam Oyun',
      'total_wins': 'Toplam Galibiyet',
      'total_score': 'Toplam Puan',
      'win_rate': 'Kazanma Oranı',
      'played': 'Oynandı',
      'best': 'En İyi',
      'average': 'Ortalama',
      'no_games_played_yet': 'Henüz oyun oynanmadı',
      'clear_statistics': 'İstatistikleri Temizle',
      'clear_statistics_confirm': 'Tüm istatistikleri silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
      'clear': 'Temizle',
      'statistics_cleared': 'İstatistikler başarıyla temizlendi',

      // Favorites Hub
      'fav_hub_title': 'Favoriler',
      'fav_leagues': 'Favori Ligler',
      'fav_clubs': 'Favori Kulüpler',
      'fav_national': 'Milli Takımlar',
      'fav_players': 'Favori Oyuncular',
      'fav_matches': 'Favori Maçlar',
      'removed': 'Kaldırıldı',
      'added': 'Eklendi',
      'add': 'Ekle',
      'add_club_hint': 'Kulüp ekle (örn. Real Madrid)',
      'no_fav_clubs': 'Henüz favori kulüp yok',
      'add_player_hint': 'Oyuncu ekle (örn. Messi)',
      'no_fav_players': 'Henüz favori oyuncu yok',
      'no_fav_national': 'Henüz favori milli takım yok',
      'add_national_hint': 'Takım ekle (örn. Brezilya)',
      'no_fav_matches': 'Henüz favori maç yok',

      // Transfers
      'transfers': 'Transferler',
      'recent_transfers': 'Son Transferler',
      'confirmed_transfers': 'onaylanan transfer',
      'no_transfers_available': 'Transfer yok',
      'search_coming_soon': 'Arama yakında geliyor!',
      'filter_options_coming_soon': 'Filtre seçenekleri yakında!',
      'search_transfers': 'Transfer ara',
      'filter_transfers': 'Transferleri filtrele',
      'age': 'Yaş',
      'position': 'Pozisyon',
      'transfer_details': 'Transfer Detayları',
      'from': 'Gönderen',
      'to': 'Alan',
      'transfer_fee': 'Transfer Ücreti',
      'contract': 'Sözleşme',
      'signed': 'İmzalandı',
      'official_club_statement': 'Resmi Kulüp Açıklaması',
      'read_from_official_source': 'Resmi kaynaktan oku',
      'could_not_open_link': 'Bağlantı açılamadı',

      // Account Hub
      'account_hub_title': 'Hesap Ayarları',
      'change_email': 'E-postayı Değiştir',
      'change_password': 'Şifreyi Değiştir',
      'change_username': 'Kullanıcı Adını Değiştir',
      'current_email': 'Mevcut E-posta',
      'new_email': 'Yeni E-posta',
      'send_verification_code': 'Doğrulama Kodu Gönder',
      'verification_code': 'Doğrulama Kodu',
      'verify_update': 'Doğrula ve Güncelle',
      'email_updated': 'E-posta Güncellendi',
      'email_updated_msg': 'E-posta adresiniz başarıyla güncellendi.',
      'ok': 'Tamam',
      
      // Password Change
      'current_password': 'Mevcut Şifre',
      'new_password': 'Yeni Şifre',
      'confirm_new_password': 'Yeni Şifreyi Onayla',
      'save_password': 'Şifreyi Kaydet',
      'required': 'Gerekli',
      'min_8_chars': 'En az 8 karakter',
      'add_uppercase': 'Büyük harf ekleyin',
      'add_lowercase': 'Küçük harf ekleyin',
      'add_digit': 'Rakam ekleyin',
      'add_symbol': 'Sembol ekleyin',
      'passwords_not_match': 'Şifreler eşleşmiyor',
      'strength': 'Güç',
      
      // Username Change
      'current_username': 'Mevcut Kullanıcı Adı',
      'new_username': 'Yeni Kullanıcı Adı',
      'save_username': 'Kullanıcı Adını Kaydet',
      'username_validation': '3-20 karakter, harf/rakam/_ sadece',
      'username_taken': 'Kullanıcı adı zaten kullanılıyor',

      // Home Screen
      'home_title': 'Classico',
      'live_matches': 'Canlı Maçlar',
      'recent_matches': 'Son Maçlar',
      'upcoming_matches': 'Gelecek Maçlar',
      'no_matches': 'Mevcut maç yok',

      // Player Info Screen
      'current_club': 'Mevcut Kulüp',
      'player_details': 'Oyuncu Detayları',
      'jersey_number': 'Forma Numarası',
      'date_of_birth': 'Doğum Tarihi',
      'nationality': 'Uyruk',
      'height': 'Boy',
      'weight': 'Kilo',
      'preferred_foot': 'Tercih Edilen Ayak',
      'season_statistics': 'Sezon İstatistikleri',
      'matches': 'Maçlar',
      'goals': 'Goller',
      'assists': 'Asistler',
      'cards': 'Kartlar',
      'minutes_played': 'Oynanan Dakika',
      'career_history': 'Kariyer Geçmişi',
      'present': 'Şu Anda',
      'added_to_favorites': 'Favorilere eklendi',
      'removed_from_favorites': 'Favorilerden kaldırıldı',
      'link_copied': 'Bağlantı kopyalandı',

      // League Standings
      'standings': 'Sıralama',
      'no_standings_available': 'Sıralama mevcut değil',
      'club_name': 'Kulüp',
      'mp_short': 'O',
      'w_short': 'G',
      'd_short': 'B',
      'l_short': 'M',
      'gf_short': 'AG',
      'ga_short': 'YG',
      'gd_short': 'AV',
      'pts_short': 'Puan',
      'champions_league': 'Avrupa Maçları',
      'europa_league': 'Avrupa Ligi',
      'relegation': 'Küme Düşme',
      'european_matches': 'Avrupa Maçları',
      'national_team_matches': 'Milli Takım Maçları',

      // News Screen
      'news_title': 'Futbol Haberleri',
      'filter_news': 'Haberleri Filtrele',
      'news_available': 'haber mevcut',
      'breaking_news': 'Son Dakika',
      'latest_news': 'Son Haberler',
      'read_more': 'Devamını Oku',

      // Welcome Screen
      'welcome_title': "Classico'ya Hoş Geldiniz",
      'welcome_subtitle': 'Canlı skorlar, haberler ve güncellemeler alın',
      'get_started': 'Başlayın',
      'login': 'Giriş Yap',
      'login_title': 'Giriş Yap',
      'login_subtitle': 'Devam etmek için giriş yapın',
      'continue_with_google': 'Google ile Devam Et',
      'sign_in_failed': 'Giriş başarısız',
      'choose_username': 'Kullanıcı adı seçin',
      'pick_unique_username': 'Benzersiz bir kullanıcı adı seçin',
      'username_visible': 'Bu diğer kullanıcılar tarafından görülebilir.',
      'username': 'Kullanıcı Adı',
      'username_hint': 'örn. footy_fan_10',
      'username_required': 'Kullanıcı adı gerekli',
      'username_min_3': 'En az 3 karakter',
      'username_invalid': 'Yalnızca harf, rakam, _ ve . kullanılabilir',
      'username_taken': 'Bu kullanıcı adı alınmış. Lütfen başka bir tane seçin.',
      'phone_number': 'Telefon Numarası',
      'add_recovery_phone': 'Kurtarma telefonu ekle',
      'phone_security': 'Hesap kurtarma ve güvenlik bildirimleri için kullanılır.',
      'phone_hint': '+90 555 123 4567',
      'phone_required': 'Telefon numarası gerekli',
      'phone_invalid': 'Lütfen geçerli bir telefon numarası girin',
      'continue': 'Devam',
      'your_preferences': 'Tercihleriniz',
      'personalize_experience': 'Deneyiminizi kişiselleştirin',
      'favorite_player': 'Favori oyuncu',
      'favorite_player_hint': 'örn. Lionel Messi',
      'favorite_team': 'Favori takım',
      'favorite_team_hint': 'örn. Barcelona',
      'national_team': 'Milli takım',
      'national_team_hint': 'örn. Arjantin',
      'preferred_league': 'Tercih edilen lig',
      'choose_league': 'Lütfen bir lig seçin',
      'required': 'Gerekli',
      'finish': 'Bitir',
      'signup': 'Kayıt Ol',
      'continue_guest': 'Misafir Olarak Devam Et',

      // Common
      'loading': 'Yükleniyor...',
      'error': 'Hata',
      'retry': 'Tekrar Dene',
      'cancel': 'İptal',
      'close': 'Kapat',
      'logout': 'Oturumu Kapat',
      'change_profile_photo': 'Profil Fotoğrafını Değiştir',
      'choose_from_gallery': 'Galeriden Seç',
      'choose_photo_from_gallery': 'Galeriden bir fotoğraf seçin',
      'take_photo': 'Fotoğraf Çek',
      'use_camera_to_take_photo': 'Yeni bir fotoğraf çekmek için kamerayı kullanın',
      'remove_photo': 'Fotoğrafı Kaldır',
      'return_to_default_photo': 'Varsayılan fotoğrafa dön',
      'favorites_count': 'Favoriler',
      'leagues': 'Ligler',
      'teams': 'Takımlar',
      'players': 'Oyuncular',
      'exit_app': 'Uygulamadan Çık',
      'exit_app_message': 'Çıkmak istediğinize emin misiniz?',
      'logout_message': 'Oturumu kapatmak istediğinize emin misiniz?',
      'logout_success': 'Başarıyla çıkış yapıldı',
      'save': 'Kaydet',
      'delete': 'Sil',
      'edit': 'Düzenle',
      'search': 'Ara',
      'filter': 'Filtrele',
      'sort': 'Sırala',
      'all': 'Hepsi',
      
      // Search Hub
      'search_hub_title': 'Arama',
      'search_players': 'Oyuncu Ara',
      'search_teams': 'Takım Ara',
      'search_leagues': 'Lig Ara',
      'search_coaches': 'Antrenör Ara',
      'search_national_teams': 'Milli Takım Ara',
      'search_stadiums': 'Stadyum Ara',
      'search_players_hint': 'Oyuncu ara...',
      'search_teams_hint': 'Takım ara...',
      'search_leagues_hint': 'Lig ara...',
      'search_coaches_hint': 'Antrenör ara...',
      'search_national_teams_hint': 'Milli takım ara...',
      'search_stadiums_hint': 'Stadyum ara...',
      'search_history': 'Arama Geçmişi',
      'clear': 'Temizle',
      'no_results_found': 'Sonuç bulunamadı',
      'top_players': 'En İyi 10 Oyuncu',
      'top_teams': 'En İyi 10 Takım',
      'top_leagues': 'En İyi 10 Lig',
      'top_coaches': 'En İyi 10 Antrenör',
      'top_national_teams': 'En İyi 10 Milli Takım',
      'top_stadiums': 'En İyi 10 Stadyum',
      'ranking': 'Sıralama',
      'teams': 'takım',
      
      // All Leagues
      'all_leagues_title': 'Lig Sıralamaları',
      'season': 'Sezon',
      'upcoming': 'Gelecek',
      'top_scorers_tab': 'Gol Krallığı',
      'top_assists_tab': 'Asistler',
      'yellow_cards_tab': 'Sarı Kartlar',
      'red_cards_tab': 'Kırmızı Kartlar',
      'clean_sheets_tab': 'Gol Yememe',
      'history_tab': 'Tarihçe',
      'goals': 'Goller',
      'assists': 'Asistler',
      'matches': 'Maçlar',
      'yellow_cards': 'Sarı Kartlar',
      'red_cards': 'Kırmızı Kartlar',
      'clean_sheets': 'Gol Yememe',
      'wins': 'Galibiyetler',
      'no_data_available': 'Veri yok',
      'club_name': 'Kulüp',
      'league_info': 'Lig Bilgisi',
      'sponsor': 'Sponsor',
      'unknown': 'Bilinmiyor',
      'champions': 'Şampiyonlar',
      'reigning_champion': 'Son Şampiyon',
      'record_champion': 'En Çok Kazanan',
      'founded': 'Kuruluş',
      'country': 'Ülke',
      'ai_translation': 'Yapay Zeka Çevirisi',
      'translated_by_ai_to': 'Yapay Zeka tarafından çevrildi:',
      'return_to_original': 'Orijinale Dön',
      'translate_news_desc': 'Bu haberi başka bir dile çevirin',
      'more_from': 'Daha fazlası:',
      'more_news_soon': 'Daha fazla haber yakında...',
      'select_language_ai': 'İstediğiniz dili seçin — Gemini AI ile desteklenmektedir',
      'write_message_here': 'Yöneticiye mesajınızı buraya yazın...',
      'please_write_message': 'Lütfen önce mesajınızı yazın',
      'sending_message': 'Mesajınız gönderiliyor...',
      'message_sent_successfully': 'Mesajınız başarıyla gönderildi. Teşekkürler!',
      'error_sending_message': 'Gönderirken bir hata oluştu. Lütfen daha sonra tekrar deneyin.',
      
      // Game Transitions & Results
      'current_score': 'Mevcut Skor',
      'you': 'Sen',
      'ai': 'Bilgisayar',
      'next_game': 'Sonraki Oyun',
      'final_score': 'Final Skoru',
      'you_won': 'Kazandın!',
      'you_lost': 'Kaybettin!',
      'its_a_tie': 'Berabere!',
      'challenge_completed': 'Meydan Okuma Tamamlandı!',
      'play_again': 'Tekrar Oyna',
      'exit': 'Çıkış',
      
      // Pause Menu
      'game_paused': 'Oyun Duraklatıldı',
      'resume': 'Devam Et',
      'restart': 'Yeniden Başlat',
      'continue': 'Devam',
      
      // Match Status
      'finished': 'Bitti',
      
      // Comments
      'comments': 'Yorumlar',
      'match_data_not_available': 'Maç verileri mevcut değil',
      'free_agent': 'Serbest Oyuncu',
      'choose_reaction': 'Tepkinizi seçin',
      'reply_to_comment': 'Yoruma cevap verin',
      'add_comment': 'Yorum ekleyin...',
      'show_all_comments': 'Tümünü Göster',
      'show_language_comments': 'Dil',
      'translate': 'Çevir',
      'show_original_text': 'Orijinal Metni Göster',
      'translation_success': 'Çeviri başarılı',
      'translation_error': 'Çeviri hatası:',
      'reply': 'Cevapla',
      'replies': 'Cevaplar',
      'inappropriate_comment': 'Uygunsuz Yorum',
      'comment_violates_guidelines': 'Yorumunuz topluluk yönergesini ihlal ediyor',
      'user_banned_24h': '24 saat boyunca yasaklandınız',
      'ban_reason': 'Yasak nedeni:',
      'remaining_ban_time': 'Kalan yasak süresi:',
      'hours': 'saat',
      'cannot_comment_while_banned': 'Yasaklıyken yorum yapamazsınız',
      'microphone_permission': 'Mikrofon İzni',
      'microphone_permission_description': 'Ses özellikleri için mikrofona erişime izin verin',
      'enable_microphone': 'Mikrofonu Etkinleştir',
      'disable_microphone': 'Mikrofonu Devre Dışı Bırak',
      'microphone_enabled': 'Mikrofon etkinleştirildi',
      'microphone_disabled': 'Mikrofon devre dışı bırakıldı',
      'add_friend': 'Arkadaş Ekle',
      'enter_username': 'Eklemek istediğiniz arkadaşın kullanıcı adını girin',
      'add_to_favorites': 'Favorilere Ekle',
      'cancel': 'İptal',
      'add': 'Ekle',
      'view': 'Görüntüle',
      'user_not_found': 'Kullanıcı Bulunamadı',
      'user_not_found_desc': 'Girdiğiniz kullanıcı adı sistemde mevcut değil',
      'friend_found': 'Arkadaş bulundu! Aşağıdan bir işlem seçin',
      'add_directly': 'Doğrudan Ekle',
      'find_friends_subtitle': 'Arkadaşlarını bul ve onlarla bağlantı kur',
      'search_username_hint': 'Kullanıcı adı ile ara...',
      'you': 'Siz',
      'message': 'Mesaj',
      'active_now': 'Şu anda aktif',
      'type_message': 'Mesaj yazın...',
      'play_with_friends': 'Arkadaşlarla Oyna',
      'challenge_your_friends': 'Arkadaşlarınıza meydan okuyun',
      'select_game': 'Oyun Seç',
      'choose_game_to_play': 'Oynamak için bir oyun seçin',
      'select_friend': 'Arkadaş Seç',
      'choose_friend_to_play': 'Birlikte oynamak için bir arkadaş seçin',
      'no_friends': 'Mevcut arkadaş yok',
      'new_message': 'Yeni Mesaj',
      'game_invite': 'Oyun Daveti',
      'sent_you_message': 'size mesaj gönderdi',
      'invites_you_to_play': 'sizi oynamaya davet ediyor',
      'football_news': 'Futbol Haberleri',
      'account_notifications': 'Hesap',
      'no_football_news': 'Henüz futbol haberi yok',
      'no_account_notifications': 'Henüz hesap bildirimi yok',
      'now': 'Şimdi',
      'minutes_ago': 'dakika',
      'hours_ago': 'saat',
      'days_ago': 'gün',
      'ago': 'önce',
      'mark_all_as_read': 'Tümünü okundu olarak işaretle',
      'clear_all': 'Tümünü temizle',
      'all_marked_as_read': 'Tümü okundu olarak işaretlendi',
      'all_notifications_cleared': 'Tüm bildirimler silindi',
      'notification_deleted': 'Bildirim silindi',
      'opened': 'Açıldı',
      'just_now': 'Şimdi',
      'minutes_ago_short': 'd',
      'hours_ago_short': 's',
      'days_ago_short': 'g',
      'weeks_ago_short': 'h',
      'no_notifications': 'Bildirim yok',
      'refresh_to_home': 'Anasayfaya yenilendi',
      
      // Login & Sign Up
      'login_title': 'Giriş Yap',
      'login_subtitle': 'Futbol Dünyasına Hoş Geldiniz',
      'continue_with_google': 'Google ile Devam Et',
      'create_new_account': 'Yeni Hesap Oluştur',
      'email': 'E-posta',
      'password': 'Şifre',
      'confirm_password': 'Şifreyi Onayla',
      'create_account': 'Hesap Oluştur',
      'already_have_account': 'Zaten bir hesabınız var mı? Giriş Yap',
      'join_our_community': 'Topluluğumuza Katılın',
      'choose_login_method': 'Tercih ettiğiniz giriş yöntemini seçin',
      'or': 'veya',
      'fill_all_fields': 'Lütfen tüm alanları doldurun',
      'passwords_not_match': 'Şifreler eşleşmiyor',
      'email_verification': 'E-posta Doğrulaması',
      'verifying_email': 'E-posta doğrulanıyor...',
      'email_verified': 'E-posta doğrulandı',
      'select_username': 'Kullanıcı Adı Seçin',
      'username': 'Kullanıcı Adı',
      'username_already_taken': 'Bu kullanıcı adı zaten alınmış',
      'username_available': 'Kullanıcı adı kullanılabilir',
      'select_favorites': 'Favorilerinizi Seçin',
      'favorite_team': 'Favori Takım',
      'favorite_player': 'Favori Oyuncu',
      'national_team': 'Milli Takım',
      'next': 'İleri',
      'skip': 'Atla',
      'finish': 'Bitir',
      'account_created': 'Hesap başarıyla oluşturuldu',
      'welcome': 'Hoş Geldiniz',
      'notification_details': 'Bildirim Detayları',
      'details': 'Detaylar',
      'close': 'Kapat',
      'confirm': 'Onayla',
      'opening_chat': 'Sohbet açılıyor...',
      'opening_game': 'Oyun açılıyor...',
      'opening_match': 'Maç açılıyor...',
      'notification_confirmed': 'Bildirim onaylandı',
      'add_league_hint': 'Favori bir lig ekleyin',
      'add_club_hint': 'Bir kulüp ekleyin (ör. Real Madrid)',
      'add_national_hint': 'Bir takım ekleyin (ör. Brezilya)',
      'add_player_hint': 'Bir oyuncu ekleyin (ör. Messi)',
      'save': 'Kaydet',
      'add': 'Ekle',
      'clear': 'Temizle',
      'search_history': 'Arama Geçmişi',
      'top_teams': 'En İyi Takımlar',
      'no_results_found': 'Sonuç bulunamadı',
      'search_teams_hint': 'Takımları ara...',
      'search_players': 'Oyuncuları Ara',
      'search_teams': 'Takımları Ara',
      'search_leagues': 'Ligleri Ara',
      'search_coaches': 'Antrenörleri Ara',
      'search_national_teams': 'Milli Takımları Ara',
      'search_stadiums': 'Stadyumları Ara',
      'search_hub_title': 'Ara',
      'cancel': 'İptal',
      'change': 'Değiştir',
      'username_change_affects': 'Kullanıcı adınızı değiştirmek, adınızın sosyal/arkadaş bölümlerinde nasıl görüneceğini etkiler.',
      'confirm_password_change': 'Şifrenizi değiştirmek istediğinizden emin misiniz?',
      'no_best_scores': 'Henüz en iyi puan yok! Rekor belirlemek için oynamaya başlayın! 🎯',
      'play_games_unlock_achievements': 'Başarıları açmak için oyunlar oynayın! 🎯',
    },
  };

  static String t(BuildContext context, String key) {
    final code = Localizations.localeOf(context).languageCode;
    final map = _t[code] ?? _t['en']!;
    return map[key] ?? key;
  }
}
